project_id = "closed-commerce"

[api]
enabled = true
schemas = ["public"]

[db]
major_version = 15

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000/**"]

[auth.email]
enable_confirmations = false
