import { formatWon } from '@closed-commerce/config';
import { Badge, Price } from '@closed-commerce/ui';
import { loadAdminSettlements } from '@/lib/admin-data';
import { AdminActionButton } from '@/components/admin-action-button';

export default async function SettlementsPage() {
  const result = await loadAdminSettlements();
  const payable = result.settlements.filter((item) => item.status === 'payable').reduce((sum, item) => sum + item.amount, 0);
  const pending = result.settlements.filter((item) => item.status === 'pending').reduce((sum, item) => sum + item.amount, 0);
  return <><div className="admin-heading"><div><p className="eyebrow">COMMISSION</p><h1>정산 관리</h1><p className="muted">주문별 snapshot 수수료를 승인·지급 상태로 관리합니다.</p></div><div><span className={`badge ${result.source === 'supabase' ? 'badge-success' : 'badge-warning'}`}>{result.source}</span> <button className="button button-primary">선택 항목 paid 처리</button></div></div><div className="admin-grid-4"><div className="card stat-card"><span className="stat-label">Payable</span><strong className="stat-value">{formatWon(payable)}</strong><span className="stat-detail">{result.settlements.filter((item) => item.status === 'payable').length}건</span></div><div className="card stat-card"><span className="stat-label">Pending</span><strong className="stat-value">{formatWon(pending)}</strong><span className="stat-detail">환불가능기간 대기</span></div><div className="card stat-card"><span className="stat-label">이번 정산기간</span><strong className="stat-value">주문 snapshot</strong><span className="stat-detail">기간별 필터 준비</span></div><div className="card stat-card"><span className="stat-label">Depth 제한</span><strong className="stat-value">L1 + L2</strong><span className="stat-detail">L3 없음</span></div></div>{result.source === 'unavailable' ? <div className="admin-note">Supabase service role 환경변수를 설정하면 실제 Commission이 표시됩니다.</div> : null}<div className="card table-wrap"><table className="data-table"><thead><tr><th>ID</th><th>수령인</th><th>Depth</th><th>기준금액</th><th>Rate</th><th>수수료</th><th>상태</th><th>액션</th></tr></thead><tbody>{result.settlements.map((item) => <tr key={item.id}><td>{item.id}</td><td>{item.owner}</td><td><Badge tone="accent">L{item.depth}</Badge></td><td><Price amount={item.base} /></td><td>{item.rate * 100}%</td><td><strong><Price amount={item.amount} /></strong></td><td><Badge tone={item.status === 'payable' ? 'success' : item.status === 'pending' ? 'warning' : 'neutral'}>{item.status}</Badge></td><td>{item.status === 'approved' ? <AdminActionButton endpoint={`/api/commissions/${item.id}`} payload={{ status: 'payable' }} label="지급가능" /> : item.status === 'payable' ? <AdminActionButton endpoint={`/api/commissions/${item.id}`} payload={{ status: 'paid' }} label="paid 처리" /> : '—'}</td></tr>)}</tbody></table></div><div className="admin-section admin-note">자동 출금은 MVP 범위에서 제외했습니다. 운영자가 승인된 payable 항목을 확인하고 정산 실행 후 paid로 수동 변경합니다.</div></>;
}
